# Generated by Django 6.0.2 on 2026-02-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dietplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('loss', 'Weight Loss'), ('gain', 'Weight Gain'), ('maintain', 'Maintain')], max_length=20)),
                ('exercise_1', models.CharField(max_length=100)),
                ('exercise_2', models.CharField(max_length=100)),
                ('exercise_3', models.CharField(max_length=100)),
            ],
        ),
    ]
