# Generated by Django 6.0.2 on 2026-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dailystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
